# (Part of) configuration for local development
services:
  backend:
  
    build:
      context: .
      target: dev

    develop:
      watch:
        - path: .
          include:
            - Dockerfile
            - pyproject.toml
          action: rebuild
        - path: .
          ignore:
            - ./**/__pycache__ 
            - Dockerfile
            - pyproject.toml
          action: sync
          target: /app
